In [1]:
import numpy as np
import pandas as pd

In [48]:
t=pd.read_csv("0000000000002429_training_titanic_x_y_train.csv")

In [49]:
t.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [50]:
t.fillna(0,inplace=True)

In [51]:
t.drop(["Name","Ticket","Cabin","Embarked","Sex"],axis=1,inplace=True)

In [94]:
Y_train=t['Survived'].values
#Y_train

In [60]:
t['Survived']=1
X_train=t.values

In [68]:
t.head()

Pclass   Age  SibSp  Parch    Fare  Survived
0       2  29.0      1      0  26.000         1
1       3   0.0      0      0   8.050         1
2       2  39.0      0      0  26.000         1
3       3  29.0      0      4  21.075         1
4       3  25.0      0      0   7.050         1

def step_wise(points,Y_train,a,m):
    M=points.shape[0]
    N=points.shape[1]
    slope_m=np.zeros(N)
    for i in range(M):
        y_pred=sig(m,points[i])
    for j in range(N):
        slope_m[j] += (-1/M)*(Y_train[i]-y_pred)*points[i,j]
    new_slope=m-a*slope_m
    return new_slope

In [96]:
def stepwise(X_train,Y_train,m,l_rate):
    m_slope=np.zeros(X_train.shape[1])
    M=len(X_train)
    for i in range(M):
        temp=0
        for j in range(len(m_slope)):
            temp+=m[j]*X_train[i][j]
        S=1/(1+np.exp(-temp))
        for k in range(len(m_slope)):
            m_slope[k] += (-1/M)*(Y_train[i]-S)*(X_train[i,k])
        m=m-l_rate*m_slope
    return m

In [100]:
def gd(points,Y_train,a,num_iter):
    m=np.zeros(points.shape[1])
    for i in range(num_iter):
        m=stepwise(points,Y_train,m,a)
    return m

In [98]:
def run():
    a=0.001
    num_iter=100
    return gd(X_train,Y_train,a,num_iter)

In [101]:
m=run()

In [125]:
def predict(X_test,m):
    Y_pred=np.zeros(len(X_test))
    for i in range(len(X_test)):
        temp=0
        for j in range(len(m)):
            temp+=m[j]*X_train[i][j]
        S=1/(1+np.exp(-temp))
        if S>=0.5:
            Y_pred[i]=1
        else:
            Y_pred[i]=0
    return Y_pred

In [103]:
X_test=pd.read_csv("0000000000002429_test_titanic_x_test.csv")
X_test.Embarked=1
X_test.fillna(0,inplace=True)
X_test.drop(["Name","Ticket","Cabin","Sex"],axis=1,inplace=True)
X_test=X_test.values

In [67]:
X_test.head()

Pclass   Age  SibSp  Parch     Fare  Embarked
0       2   8.0      1      1  36.7500         1
1       1  49.0      0      0  25.9292         1
2       3   0.0      0      0   7.7375         1
3       2  24.0      2      1  27.0000         1
4       1  36.0      0      0  26.2875         1

In [126]:
y=predict(X_test,m)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [93]:
Y_train.values

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

In [120]:
m

array([0.31919936, 0.61753025, 0.01339358, 0.00883848, 0.70021263,
       0.15727616])